package projecteuler

import scala.collection.mutable.LinkedList

/**
 * Created by IntelliJ IDEA.
 * User: adamj
 * Date: 8/2/11
 * Time: 10:45 AM
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

object Problem2 {
    /**
     * This function generates a Fibonacci Sequence in an iterative fashion
     */
    def Fibonacci(maxValue: Int): List[Int] = {
        var ret = 1 :: 2 :: Nil
        while(ret.last <= maxValue) {
            ret = ret :+ ret.drop(ret.length - 2).sum
        }
        return ret.dropRight(1)
    }

    /**
     * Used the Fibonacci function above to sum all even numbers in the sequence
     */
    def Stupid(max: Int): Int = {
        return Fibonacci(max).filter(_ % 2 == 0).sum
    }

}